title: "Mustafa Cem Gezici"
description: "Global History & History & Economics â€” R, QGIS, Archival Research"
theme: jekyll-theme-cayman   # istersen jekyll-theme-minimal veya jekyll-theme-slate de yazabilirsin
show_downloads: false
markdown: kramdown
